name: test

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 7.0.0

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '14'
          cache: 'pnpm'

      - name: test
        run: pnpm i && pnpm test

      - name: report
        uses: codecov/codecov-action@v1.1.1
        env:
          CI: true
